#!/usr/local/bin/bash

# remotely download latest backup file

BASEDIR=/home/pfSensePortal
CONFIG_FILE=config-router-`date +%Y%m%d%H%M%S`.xml

# get pfSense login details
source $BASEDIR/config.txt

# login
wget -qO/dev/null --keep-session-cookies --save-cookies cookies.txt \
 --post-data "login=Login&usernamefld=`echo $USER`&passwordfld=`echo $PASSWD`" \
 --no-check-certificate https://$PF_IP/diag_backup.php

# get the stuff
wget --keep-session-cookies --load-cookies cookies.txt \
 --post-data 'Submit=download&donotbackuprrd=yes' https://$PF_IP/diag_backup.php \
 --no-check-certificate -O $CONFIG_FILE

rm cookies.txt

scp /home/pfSensePortal/misc/$CONFIG_FILE backup@dev.pih-emr.org:malawi/pfsense-21
mv /home/pfSensePortal/misc/$CONFIG_FILE /home/local_backup_sequences

SUBJECT="pfSense: Backup sync'ed to local drive and Boston"
BODY="(mail generated by script pfSense:///home/pfSensePortal/misc/do-backup.sh)"

perl -I /usr/local/lib/perl5/site_perl/5.10.1/ -I /usr/local/lib/perl5/site_perl/5.10.1/mach $BASEDIR/send_gmail.perl "$SUBJECT" "$BODY"
